config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  
  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
  
  resources :categories, only: [:create, :new, :show]
  
  resources :users, only: [:create, :show, :edit, :update]
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  
  has_many :post_categories
  has_many :posts, through: :post_categories
  
  validates :name, presence: true, uniqueness: true
  
  sluggable_column :name
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  
  belongs_to :user
  belongs_to :footstep
  
  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  PER_PAGE = 10
  
  include Voteable
  include Sluggable
  
  belongs_to :user
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  
  validates :title, presence: true
  validates :url, presence: true
  validates :description, presence: true
  
  sluggable_column :title
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  include Sluggable
  
  has_many :posts
  has_many :comments
  has_many :votes
  
  has_secure_password validations: false
  validates :password, presence: true, on: :create, length: {minimum: 6}
  validates :username, presence: true, uniqueness: true
  
  sluggable_column :username
  
  def admin?
    self.role == 'admin'
  end
  
  def moderator?
    self.role == 'moderator'
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
  
  validates_uniqueness_of :user, scope: [:voteable_id, :voteable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
      
  def require_user
    access_denied unless logged_in?
  end
  
  def require_admin
    access_denied unless logged_in? and current_user.admin?
  end
  
  def access_denied
    flash['error'] = "You can't do that."
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController  
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]
  
  def show
    @category = Category.find_by slug: params[:id]
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      flash['notice'] = "Category was successfully created."
      redirect_to root_path
    else
      render :new
    end
  end
  
  def category_params
    params.require(:category).permit!
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def create
    @post = Post.find_by slug: params[:post_id]
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash['notice'] = "Your comment was successfully created."
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end
  
  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, user: current_user, vote: params[:vote])
    respond_to do |format|
      format.html do
        if @vote.errors.any?
          flash['error'] = "You can only vote once."
        else
          flash['notice'] = "Your vote was counted."
        end
        redirect_to :back
      end
      format.js
    end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update]
  
  def index
    @posts = (Post.all.limit(Post::PER_PAGE).offset(params[:offset])).sort_by{|x| x.total_votes}.reverse
    @pages = (Post.all.size / Post::PER_PAGE) 
    @pages += 1 if (Post.all.size % Post::PER_PAGE) > 0
  end
  
  def show
    @comment = Comment.new
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      flash['notice'] = "Your post was successfully created."
      redirect_to posts_path
    else
      render :new
    end
  end
  
  def edit 
  end
  
  def update    
    if @post.update(post_params)
      flash['notice'] = "Your post was successfully updated."
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def vote
    @vote = Vote.create(voteable: @post, user: current_user, vote: params[:vote])    
    respond_to do |format|
      format.html do
        if @vote.errors.any?
          flash['error'] = "You can only vote once."
        else
          flash['notice'] = "Your vote was counted."
        end
        redirect_to :back
      end
      format.js
    end
  end
  
  private
  def post_params
    params.require(:post).permit!
  end
  
  def set_post
    @post = Post.find_by slug: params[:id]
  end
  
  def require_same_user
    access_denied unless logged_in? and (current_user == @post.user || current_user.admin?)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash['notice'] = "You're logged in."
      redirect_to root_path
    else
      flash['error'] = "There is something wrong with your username or password."
      redirect_to login_path
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash['notice'] = "You're logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]
  
  def show
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash['notice'] = "Profile was successfully created. You're now logged in."
      redirect_to root_path
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash['notice'] = "Your profile was successfully updated."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password, :time_zone)
  end
  
  def set_user
    @user = User.find_by slug: params[:id]
  end
  
  def require_same_user
    access_denied unless logged_in? and (current_user == @user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end
  
  def display_datetime(date)
    if logged_in? && !current_user.time_zone.blank?
      date = date.in_time_zone(current_user.time_zone)
    end
    date.strftime("%m/%d/%Y %l:%M%P %Z")
  end
end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Create a New Category' %>

<%= render 'shared/errors', obj: @category %>

<div class='well'>
  <%= form_for @category do |f| %>
    <div class='control-group'>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
  <%= f.submit "Create Category", class: "btn btn-primary" %>
  <% end %>
</div>

<div style="column-count: 2"> 
  <h5>Current categories include:</h5>
  <% Category.all.sort{|a,b| a['name']<=>b['name']}.each do |category| %>
    <ul>
      <li><%= link_to category.name, category_path(category) %></li>
    </ul>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>
<%= render 'shared/content_title', title: header %>

<% @category.posts.each do |post| %>
  <%= render '/posts/post', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class='row'>  
  <%= render 'shared/vote_errors' %>
  
  <div class='well span0 text-center'>
    <% if logged_in? %>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %> 
        <i class='icon-arrow-up'></i>  
      <% end %> 
      <br/>
    <% end %>
    <span id="votes_comment_<%= comment.id %>"><%= comment.total_votes %> votes</span>
    <br/>
    <% if logged_in? %>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %> 
        <i class='icon-arrow-down'></i>          
      <% end %> 
    <% end %>
  </div>
  <div class="well span8">
    <p>"<%= comment.body %>"</p>
    <p>
      <span class="quiet">
        <% if show_post %>
          on <%= link_to comment.post.title, post_path(comment.post) %>
          <br/>
        <% end %>
        by: <%= link_to comment.user.username, user_path(comment.user) %>
        <small>at <%= display_datetime(comment.created_at) %></small>
      </span>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.errors.any? %>
  $("#vote_error").show();
  $("#vote_error").click(function(){
    $("#vote_error").hide()
  });
<% else %>
  $("#votes_comment_<%= @comment.id %>").html("<%= @comment.total_votes %> votes");
  $("#vote_success").show();
  $("#vote_success").click(function(){
    $("#vote_success").hide()
  });
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>
<div class='btn-group nav_item'>
  <%= link_to '#', class: 'btn dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    Categories <span class='caret'></span>
  <% end %>
      <ul class='dropdown-menu'>
      <% Category.all.sort{|a,b| a['name']<=>b['name']}.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
      <% end %>
      <% if logged_in? and current_user.admin? %>
        <li class='divider'></li>
        <li>
          <%= link_to(new_category_path) do %>
            <i class='icon-plus'></i>
            New Category
          <% end %>
        </li>
      <% end %>  
    </ul>
</div>
<% if logged_in? %>
  <div class='btn'>
    <%= link_to 'New Post', new_post_path %>
  </div>
  <div class='btn-group nav_item'>
    <%= link_to '', class: 'btn dropdown-toggle', 'data-toggle' => 'dropdown' do %>
      <%= current_user.username %> <span class='caret'></span>
    <% end %>
      <ul class='dropdown-menu'>
        <li><%= link_to edit_user_path(current_user) do %>
          <i class='icon-pencil'></i>
          Edit Profile
          <% end %>
        </li>
        <li><%= link_to user_path(current_user) do %>
          <i class='icon-user'></i>
          View Profile
          <% end %>
        </li> 
        <li><%= link_to logout_path(current_user) do %>
          <i class='icon-circle-arrow-left'></i>
          Logout
          <% end %>
        </li> 
      </ul>
  </div>
<% else %>
  <div class='btn'>
    <%= link_to 'Register', register_path %>
  </div>
  <div class='btn'>
    <%= link_to 'Log In', login_path %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DG - Postit Clone</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class='well span8'>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'span5' %>
    </div>
    <div class='control-group'>
      <%= f.label :url %>
      <%= f.text_field :url, class: 'span5' %>
    </div>
    <div class='control-group'>
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5, class: 'span5' %>
    </div>
    <div class='control-group'>
      <%= f.label "Categories" %>
      <%= f.collection_check_boxes :category_ids, Category.all.sort{|a,b| a['name'] <=> b['name']}, :id, :name do |box| %>
        <%= box.label(class: 'checkbox inline') {box.check_box(class: 'checkbox') + box.text} %>
      <% end %>
    </div>
    <%= f.submit(@post.new_record? ? "Create Post" : "Update Post", class: "btn btn-primary") %>
    <p class='btn'>
      <%= link_to 'Cancel', @post.new_record? ? root_path : post_path(@post) %>
      <br/>
    </p>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  
  <%= render 'shared/vote_errors' %>
  
  <div class='well span0 text-center'>
    <% if logged_in? %>
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %> 
    <i class='icon-arrow-up'></i>  
    <% end %> 
    <br/>
    <% end %>
    <span id='votes_post_<%= post.to_param %>'><%= post.total_votes %> votes</span>
    <br/>
    <% if logged_in? %>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %> 
    <i class='icon-arrow-down'></i>          
    <% end %> 
    <% end %>
  </div>

  <div class="well span8">
    <%= render post.categories %>
    <h4><%= link_to post.title, post_path(post) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">posted by: <%= link_to post.user.username, user_path(post.user) %>
        <small>at <%= display_datetime(post.created_at) %></small>
      </span>
      <span>
        <small>
          <%= link_to("#{post.comments.size} comments", post_path(post)) %>
        </small>
      </span>
    </p>
  </div>
</div> 

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

<div class="pagination pagination-centered">
  <ul>
    <% @pages.times do |page| %>
      <% if (params[:offset].nil? && page == 0) || params[:offset].to_s == (page * Post::PER_PAGE).to_s %>
        <li class='disabled'><a><%= "#{page+1}" %></a></li>
      <% else %>
      <li><%= link_to "#{page+1}", posts_path(offset: page * Post::PER_PAGE) %></li>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a New Post' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: (link_to @post.title, fix_url(@post.url)) %>

<p> <%= @post.description %>
  <hr/>
</p>
<p>
  <span class="quiet">posted by: <%= link_to @post.user.username, user_path(@post.user) %>
    <small>at <%= display_datetime(@post.created_at) %></small>
  </span>
</p>
<% if logged_in? && (current_user == @post.user || current_user.admin?) %>
  <p class='btn'>
    <%= link_to 'Edit Post', edit_post_path(@post) %>
  </p>
<% end %>
<p class='btn'>
  <%= link_to 'Back to All Posts', posts_path %>
</p>

<hr/>

<% if logged_in? %>
  <div class="row">
    <div class="well span8">
      <%= render 'shared/errors', obj: @comment %>
      <%= form_for [@post, @comment] do |f| %>
        <div class='control-group'>
          <%= f.label :body, "Leave a Comment:" %>
          <%= f.text_area :body, rows: 5, class: "span5" %>
          <br/>
          <%= f.submit "Create Comment", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<% @post.reload.comments.each do |comment| %>
  <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.errors.any? %>
  $("#vote_error").show();
  $("#vote_error").click(function(){
    $("#vote_error").hide()
  });
<% else %>
  $("#votes_post_<%= @post.to_param %>").html("<%= @post.total_votes %> votes");
  $("#vote_success").show();
  $("#vote_success").click(function(){
    $("#vote_success").hide()
  });
<% end %>

app/views/shared/_content_title.html.erb
<p class="lead">
  <%= title %>
  <hr/>
</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-error">
    <h5>Did not save due to the following error(s):</h5>
    <ul>
      <%= obj.errors.full_messages do |msg| %>
        <li><%= msg %></li>
        <br/>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_vote_errors.html.erb
<div id='vote_error' class="alert alert-error span12" style='display: none'>   
  <p>You can only vote once.</p>
</div>

<div id='vote_success' class="alert alert-success span12" style='display: none'>    
  <p>Your vote was counted.</p>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class='well span8'>
  <%= form_for @user do |f| %>
    <div class='control-group'>
      <%= f.label :username %>
      <%= f.text_field :username, class: 'span5' %>
    </div>
    <div class='control-group'>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'span5' %>
    </div>
    <div class='control-group'>
      <%= f.label :time_zone %>
      <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name, class: 'span5' %>
    </div>
    <%= f.submit (@user.new_record? ? "Register" : "Update Profile"), class: "btn btn-primary" %>
    <p class='btn'>
      <%= link_to 'Cancel', root_path %>
    <br/>
    </p>
    <p>    
      <br/>
      <% if !logged_in? %>
      Already a user? 
      <%= link_to 'Log in', login_path %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: 'Update Your Profile' %>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: 'Register' %>

<%= render 'form' %>

app/views/users/show.html.erb
<% header = "Profile: #{@user.username}".html_safe %>
<%= render 'shared/content_title', title: header %>

<div class="row">
  <div class='well span8'>
    <p><strong>Username:</strong> <%= @user.username %></p>
    <p><strong>Time Zone:</strong> <%= @user.time_zone %></p>
    <p><strong>Joined:</strong> <%= display_datetime(@user.created_at) %></p>
    <p><strong>Latest Post:</strong> <%= display_datetime(@user.posts.last.created_at) %>
  </div>
</div>

<div>
  <h5><%= @user.username %>'s Activity</h5>
  <ul class='nav nav-tabs'>
    <li class='<%= 'active' if params[:tab].nil? %>'>
      <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
    </li>
    <li class='<%= 'active' if params[:tab] == 'comments' %>'>
      <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
    </li>
  </ul>
</div>

<div>
  <% if params[:tab].nil? %>
    <% @user.posts.each do |post| %>
      <%= render 'posts/post', post: post %>
    <% end %>
  <% elsif params[:tab] == 'comments' %>
    <% @user.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment, show_post: true %>
    <% end %>
  <% end %>
</div>